### ISSUE TITLE
Missing eligibilityOptions for many measures.

### ISSUE THREAD

**Issue by danielson317** [CMSgov/qpp-measures-data#161]
The /measures/2018/measures-data.json (and xml) file are missing eligibilityOptions entries for many of it's measures. This specifically includes measureID: "005" but many others are also affected.

**Comment by tetraptych** [comment]
Currently, the `eligibilityOptions` and `performanceOptions` keys only exist for claims-based quality measures. These values are used in [this repository](https://github.com/CMSgov/qpp-claims-to-quality-public) to calculate the claims-based quality measures from external sources of claims data (e.g., third-party databases or csv files).

Would be great to know more about your potential use case for having these fields on other measures. My understanding is that these fields might also make sense for registry measures (though often the registry version and the claims version of same measure have non-trivial differences).

**Comment by danielson317** [comment]
Perhaps I misunderstood the purpose of this repository or perhaps I don't understand the Denominator's usage in the official documents?

I was looking for a complete machine-readable list of Quality Measures. If you look at the [official document for "005"](https://qpp.cms.gov/docs/QPP_quality_measure_specifications/Claims-Registry-Measures/2018_Measure_005_Registry.pdf) the denominator which appears to be equivalent to eligibilityOptions is present but this machine readable copy does not have them.

**Comment by tetraptych** [comment]
That makes perfect sense. You're correct in treating this repository as a machine-readable list of measures, and you're correct in noting that there is information contained in the measure specification pdfs that is **not** included here. For example, the "Clinical Recommendation Statements" section of the pdf is not represented in `measures-data.json`. More to the point, the denominator and numerator information from the pdfs is not included for registry measures.

Note that there can be multiple measure specifications for a single measureID when there are multiple valid submission methods. For example, Measure 001 has both a [registry specification](https://qpp.cms.gov/docs/QPP_quality_measure_specifications/Claims-Registry-Measures/2018_Measure_001_Registry.pdf) and a [claims specification](https://qpp.cms.gov/docs/QPP_quality_measure_specifications/Claims-Registry-Measures/2018_Measure_001_Claims.pdf). The `eligibilityOptions` and `performanceOptions` for this measure are populated using the claims specification, so in cases where both submission methods are available, only the information from the claims specification is used. 

I definitely agree that the current situation is misleading, since from a registry user's perspective it looks like some measures have `eligibilityOptions` and some measures don't, seemingly at random. I see four potential paths forward:

1. Update [the schema](https://github.com/CMSgov/qpp-measures-data/blob/master/measures/2018/measures-schema.yaml#L144-L151) to indicate that these fields only apply to claims-based quality measures.
1. Nest the claims-specific fields under a new key to make it clear that these fields only apply to claims-based quality measures.
1. Remove these fields across the board.
1. Populate these fields for registry measures as well as claims-based measures.

Options 1, 2, and 3 would help clarify the meaning of these fields, but would not be particularly helpful for use cases that require the information to be available for all quality measures in `measures-data.json`. Option 4 would address this issue, but might not be aligned with the intended purpose of this repository.  

Tagging the code owners (@marimiyachi @kencheeto @samskeller @kalvinwang) to hear their thoughts.

P.S.: You may find [the supporting documents](https://www.cms.gov/Medicare/Quality-Payment-Program/Resource-Library/2018-Quality-Measure-Specifications-supporting-documents.zip) useful. The source of truth for what codes are parts of what measures is included here under the name `2018_Registry_SingleSource_v2.2.xlsx` or `2018_Claims_SingleSource_2.2.xlsx`, depending on the submission method. The claims version of the document is what is used to populate the `eligibilityOptions` in `measures-data.json`.
