### ISSUE TITLE
2019 Quality Measure UUID values

### ISSUE THREAD

**Issue by jacobmakowski** [CMSgov/qpp-measures-data#231]
Population UUIDs are missing from the /2019/quality-strata.csv file. When will these be added? Thanks!

**Comment by sarahnw** [comment]
Information about measures is added as it becomes available. I know these are being worked on currently. Generally though UUIDs take a little longer to compile together than basic measure information.

**Comment by jacobmakowski** [comment]
It looks like these values were added in https://github.com/CMSgov/qpp-measures-data/pull/232 
Can the values be added to qpp-measures-data/util/measures/2019/quality-measures.csv and qpp-measures-data/util/measures/2019/quality-strata.csv as well?

**Comment by sarahnw** [comment]
The process to add measures, strata, and UUIDs involve separate files and separate updates to the repository in order to deliver information in a timely manner. You can view the UUIDs in the repository as a part of measure schema now that #232 is complete: https://github.com/CMSgov/qpp-measures-data/blob/master/measures/2019/measures-data.json
