### ISSUE TITLE
Missing 2019 benchmark data

### ISSUE THREAD

**Issue by mattmerrifield** [CMSgov/qpp-measures-data#235]
Hi there!

I noticed `benchmarks/2019.json` contains just an empty array (2018 has the data I would need in it, but for the wrong year). 

What's the timeline for populating the latest benchmark data? I'm having a hard time sourcing this data from anywhere else on the internet, and the qpp.cms.gov website has a broken link to even the 2018 stuff.

**Comment by kalvinwang** [comment]
Hi @mattmerrifield, the 2019 historical benchmarks are now published as part of the 1.14.0 release here: https://github.com/CMSgov/qpp-measures-data/releases/tag/v1.14.0

Note that the 2019 historical benchmarks are preliminary because 2019 measures data is preliminary; e.g. 2019 measures don't yet include measureSpecification fields, which can affect benchmarks for certain measures. 

Where's the broken link? I can request that it be fixed.

**Comment by jacobmakowski** [comment]
@kalvinwang - thanks for updating the 2019 historical benchmarks. Any idea when the measureSpecification will be added or when the 2019 file (https://github.com/CMSgov/qpp-measures-data/blob/master/benchmarks/2019.json) will include the web interface benchmarks?
